version: '3.8'

services:
  mariadb:
    image: mariadb:11.5
    container_name: mariadb
    env_file:
      - .env.db
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network

  wordpress:
    image: wordpress:php8.3-fpm-alpine
    container_name: wp
    env_file:
      - .env.wp
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - wp_network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - wp_network

volumes:
  wordpress_data:
  mariadb_data:

networks:
  wp_network:
    driver: bridge